development:
  adapter: postgresql
  encoding: unicode
  database: erroneous_development

test:
  adapter: postgresql
  encoding: unicode
  database: erroneous_test

production:
  adapter: postgresql
  encoding: unicode
  database: erroneous_production
